# Generated by Django 3.0.4 on 2020-06-28 11:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentList',
            fields=[
                ('DName', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='部门名称')),
                ('DDescribe', models.CharField(max_length=30, verbose_name='部门描述')),
                ('DNum', models.IntegerField(verbose_name='部门人数')),
            ],
        ),
        migrations.CreateModel(
            name='StaffInfo',
            fields=[
                ('E_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('Name', models.CharField(max_length=6, verbose_name='姓名')),
                ('Sex', models.CharField(max_length=1, verbose_name='性别')),
                ('Birth', models.DateField(default=datetime.date(2020, 6, 28), verbose_name='出生日期')),
                ('Hiredate', models.DateField(default=datetime.date(2020, 6, 28), verbose_name='入职日期')),
                ('Age', models.IntegerField(verbose_name='年龄')),
                ('Department', models.CharField(max_length=10, verbose_name='部门')),
                ('Position', models.CharField(max_length=10, verbose_name='职位')),
                ('Phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('Mail', models.CharField(max_length=16, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('User', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='用户名')),
                ('Password', models.CharField(max_length=16, verbose_name='密码')),
                ('E_id', models.IntegerField(verbose_name='用户ID')),
                ('UserTag', models.IntegerField(verbose_name='用户类型')),
            ],
        ),
        migrations.CreateModel(
            name='BasicSalary',
            fields=[
                ('E_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wage.StaffInfo', verbose_name='用户ID')),
                ('Name', models.CharField(max_length=6, verbose_name='姓名')),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='基础工资')),
                ('Insurance', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='保险')),
                ('AbsentDay', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='缺勤扣款/天')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=6, verbose_name='姓名')),
                ('GrantTime', models.DateTimeField(default=datetime.datetime(2020, 6, 28, 11, 43, 43, 92467), verbose_name='发放时间')),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='基础工资')),
                ('Insurance', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='保险')),
                ('Penalty', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='罚款')),
                ('Royalty', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='提成')),
                ('Money', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='最终金额')),
                ('E_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wage.StaffInfo', verbose_name='用户ID')),
            ],
        ),
        migrations.CreateModel(
            name='PositionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PName', models.CharField(max_length=10, verbose_name='职位名称')),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='基础工资')),
                ('PforDname', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='wage.DepartmentList', verbose_name='所属部门')),
            ],
        ),
        migrations.CreateModel(
            name='CheckRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheckTime', models.DateTimeField(default=datetime.datetime(2020, 6, 28, 11, 43, 43, 93464), verbose_name='签到时间')),
                ('E_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wage.StaffInfo', verbose_name='用户ID')),
            ],
        ),
    ]
