# Generated by Django 3.0.4 on 2020-06-29 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkrecord',
            name='CheckTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 14, 52, 26, 352806), verbose_name='签到时间'),
        ),
        migrations.AlterField(
            model_name='salarygrant',
            name='GrantTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 14, 52, 26, 351742), verbose_name='发放时间'),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='Birth',
            field=models.DateField(default=datetime.date(2020, 6, 29), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='Hiredate',
            field=models.DateField(default=datetime.date(2020, 6, 29), verbose_name='入职日期'),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='Mail',
            field=models.CharField(max_length=25, verbose_name='邮箱'),
        ),
    ]
