# Generated by Django 3.0.4 on 2020-06-29 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0002_auto_20200629_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='User',
            new_name='WUser',
        ),
        migrations.AlterField(
            model_name='checkrecord',
            name='CheckTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 22, 8, 23, 348521), verbose_name='签到时间'),
        ),
        migrations.AlterField(
            model_name='salarygrant',
            name='GrantTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 22, 8, 23, 348521), verbose_name='发放时间'),
        ),
    ]
